from __future__ import annotations

import re
from typing import Any, Dict, List, Optional


def _derive_doctor_email(name: str) -> str:
    cleaned = name.lower()
    for prefix in ("dr. ", "prof. ", "professor "):
        if cleaned.startswith(prefix):
            cleaned = cleaned[len(prefix):]
    slug = re.sub(r"[^a-z0-9]+", ".", cleaned).strip(".")
    return f"{slug}@ovacare-referrals.lk"


def get_doctors_catalog() -> List[Dict[str, Any]]:
    """Static doctor catalog with real Sri Lankan gynecologists.

    In production this would come from a DB.
    """
    doctors = [
        # Colombo Doctors
        {
            "id": 1,
            "name": "Dr. Suranga Hettipathirana",
            "specialty": "Obstetrics & Gynaecology (VOG)",
            "rating": 4.9,
            "reviews": 324,
            "experience": "20 years",
            "location": "Colombo 07, Sri Lanka",
            "distance": "2.1 km",
            "image": "👨‍⚕️",
            "verified": True,
            "acceptsInsurance": ["SLIMHC", "Lanka IOC Health", "Ceylinco Healthcare"],
            "availableToday": True,
            "consultationFee": "LKR 4,500",
            "about": "Highly experienced Consultant Obstetrician & Gynaecologist. Expert in PCOS management, hormonal disorders, and gynaecological health in Sri Lankan women.",
            "credentials": [
                "MBBS - University of Colombo",
                "MD - Obstetrics & Gynaecology",
                "MRCOG - Royal College of Obstetricians and Gynaecologists, UK",
                "Fellowship - Reproductive Medicine",
            ],
            "languages": ["Sinhala", "Tamil", "English"],
            "officeHours": "Mon-Fri: 8AM-6PM, Sat: 9AM-1PM",
            "nextAvailable": "Today, 2:30 PM",
            "categories": ["gynecology"],
            "telemedicine": True,
            "phone": "+94 11 234 5671",
        },
        {
            "id": 2,
            "name": "Dr. Nalinda Rodrigo",
            "specialty": "Obstetrics & Gynaecology",
            "rating": 4.8,
            "reviews": 289,
            "experience": "18 years",
            "location": "Colombo 05, Sri Lanka",
            "distance": "2.8 km",
            "image": "👩‍⚕️",
            "verified": True,
            "acceptsInsurance": ["Janashakthi Insurance", "Ceylinco General", "AIA Insurance"],
            "availableToday": True,
            "consultationFee": "LKR 4,000",
            "about": "Consultant Obstetrician & Gynaecologist specializing in PCOS, reproductive health, and women's wellness. Known for patient-centered approach.",
            "credentials": [
                "MBBS - University of Colombo",
                "MD - Obstetrics & Gynaecology",
                "MRCOG - UK",
            ],
            "languages": ["Sinhala", "Tamil", "English"],
            "officeHours": "Tue-Sat: 9AM-5PM",
            "nextAvailable": "Today, 3:00 PM",
            "categories": ["gynecology"],
            "telemedicine": True,
            "phone": "+94 11 234 5672",
        },
        {
            "id": 3,
            "name": "Dr. Dharshana Somirathne",
            "specialty": "Obstetrics & Gynaecology (VOG)",
            "rating": 4.7,
            "reviews": 256,
            "experience": "16 years",
            "location": "Colombo 03, Sri Lanka",
            "distance": "1.9 km",
            "image": "👩‍⚕️",
            "verified": True,
            "acceptsInsurance": ["Sri Lanka Insurance", "Co-operative Insurance", "Union Assurance"],
            "availableToday": False,
            "consultationFee": "LKR 3,800",
            "about": "Senior Consultant Gynaecologist with expertise in PCOS, hormonal imbalances, and reproductive endocrinology for Sri Lankan women.",
            "credentials": [
                "MBBS - University of Colombo",
                "MD - Obstetrics & Gynaecology",
                "Diploma - Reproductive Medicine",
            ],
            "languages": ["Sinhala", "English"],
            "officeHours": "Mon-Fri: 9AM-5PM, Sat: 10AM-2PM",
            "nextAvailable": "Tomorrow, 10:00 AM",
            "categories": ["gynecology"],
            "telemedicine": True,
            "phone": "+94 11 234 5673",
        },
        {
            "id": 4,
            "name": "Dr. D Maruthini",
            "specialty": "Fertility & IVF Specialist",
            "rating": 4.9,
            "reviews": 312,
            "experience": "19 years",
            "location": "Colombo 07, Sri Lanka",
            "distance": "2.3 km",
            "image": "👩‍⚕️",
            "verified": True,
            "acceptsInsurance": ["SLIMHC", "Lanka IOC Health", "Ceylinco Healthcare"],
            "availableToday": True,
            "consultationFee": "LKR 5,500",
            "about": "Consultant Gynaecologist, Fertility Specialist, and IVF Expert. Specializes in PCOS management, subfertility, and assisted reproductive techniques.",
            "credentials": [
                "MBBS - University of Colombo",
                "MD - Obstetrics & Gynaecology",
                "Fellowship - Reproductive Medicine & IVF",
                "MRCOG - UK",
            ],
            "languages": ["Sinhala", "Tamil", "English"],
            "officeHours": "Mon-Fri: 8AM-6PM, Sat: 9AM-12PM",
            "nextAvailable": "Today, 4:00 PM",
            "categories": ["gynecology", "fertility"],
            "telemedicine": True,
            "phone": "+94 11 234 5674",
        },
        {
            "id": 5,
            "name": "Dr. Ajitha Wijesundara",
            "specialty": "Obstetrics & Gynaecology",
            "rating": 4.7,
            "reviews": 198,
            "experience": "15 years",
            "location": "Colombo 05, Sri Lanka",
            "distance": "3.2 km",
            "image": "👩‍⚕️",
            "verified": True,
            "acceptsInsurance": ["Softlogic Insurance", "HNB Assurance", "Allianz Insurance"],
            "availableToday": True,
            "consultationFee": "LKR 3,500",
            "about": "Consultant Obstetrician & Gynaecologist with focus on women's health, PCOS management, and holistic reproductive care.",
            "credentials": [
                "MBBS - University of Sri Jayewardenepura",
                "MD - Obstetrics & Gynaecology",
                "MRCOG - UK",
            ],
            "languages": ["Sinhala", "Tamil", "English"],
            "officeHours": "Mon-Sat: 8AM-4PM",
            "nextAvailable": "Today, 1:30 PM",
            "categories": ["gynecology"],
            "telemedicine": True,
            "phone": "+94 11 234 5675",
        },
        {
            "id": 6,
            "name": "Dr. Kamani Mayadunna",
            "specialty": "Obstetrics & Gynaecology",
            "rating": 4.8,
            "reviews": 267,
            "experience": "17 years",
            "location": "Colombo 04, Sri Lanka",
            "distance": "2.5 km",
            "image": "👩‍⚕️",
            "verified": True,
            "acceptsInsurance": ["Ceylinco Life", "Sri Lanka Insurance", "MBSL Insurance"],
            "availableToday": False,
            "consultationFee": "LKR 4,200",
            "about": "Experienced Consultant Obstetrician & Gynaecologist specializing in PCOS, menstrual disorders, and women's reproductive health.",
            "credentials": [
                "MBBS - University of Kelaniya",
                "MD - Obstetrics & Gynaecology",
                "Diploma - Gynaecological Ultrasound",
            ],
            "languages": ["Sinhala", "English"],
            "officeHours": "Tue-Sat: 9AM-5PM",
            "nextAvailable": "Tomorrow, 11:00 AM",
            "categories": ["gynecology"],
            "telemedicine": True,
            "phone": "+94 11 234 5676",
        },
        {
            "id": 7,
            "name": "Prof. A.K. Probhodana Ranaweera",
            "specialty": "Obstetrics & Gynaecology (VOG)",
            "rating": 4.9,
            "reviews": 401,
            "experience": "25 years",
            "location": "Colombo 07, Sri Lanka",
            "distance": "2.0 km",
            "image": "👨‍⚕️",
            "verified": True,
            "acceptsInsurance": ["SLIMHC", "Lanka IOC Health", "Ceylinco Healthcare"],
            "availableToday": True,
            "consultationFee": "LKR 6,000",
            "about": "Professor and Senior Consultant Obstetrician & Gynaecologist. Leading expert in PCOS, reproductive medicine, and women's endocrine health.",
            "credentials": [
                "MBBS - University of Colombo",
                "MD - Obstetrics & Gynaecology",
                "MRCOG - UK",
                "Fellowship - Reproductive Endocrinology",
            ],
            "languages": ["Sinhala", "Tamil", "English"],
            "officeHours": "Mon-Fri: 8AM-6PM",
            "nextAvailable": "Today, 5:00 PM",
            "categories": ["gynecology"],
            "telemedicine": True,
            "phone": "+94 11 234 5677",
        },
        # Kandy Doctors
        {
            "id": 8,
            "name": "Dr. A.C. Mohammed Musthaq",
            "specialty": "Obstetrics & Gynaecology with Scanning",
            "rating": 4.7,
            "reviews": 234,
            "experience": "16 years",
            "location": "Kandy, Sri Lanka",
            "distance": "3.2 km",
            "image": "👨‍⚕️",
            "verified": True,
            "acceptsInsurance": ["Janashakthi Insurance", "Ceylinco General", "AIA Insurance"],
            "availableToday": True,
            "consultationFee": "LKR 3,500",
            "about": "Consultant Obstetrician & Gynaecologist with expertise in ultrasound scanning and PCOS management in up-country Sri Lanka.",
            "credentials": [
                "MBBS - University of Peradeniya",
                "MD - Obstetrics & Gynaecology",
                "Diploma - Ultrasound Imaging",
            ],
            "languages": ["Sinhala", "English", "Tamil"],
            "officeHours": "Tue-Sat: 9AM-5PM",
            "nextAvailable": "Today, 10:30 AM",
            "categories": ["gynecology"],
            "telemedicine": True,
            "phone": "+94 81 234 5671",
        },
        {
            "id": 9,
            "name": "Dr. Harindra Ranaweera",
            "specialty": "Obstetrics & Gynaecology",
            "rating": 4.6,
            "reviews": 189,
            "experience": "14 years",
            "location": "Kandy, Sri Lanka",
            "distance": "3.5 km",
            "image": "👨‍⚕️",
            "verified": True,
            "acceptsInsurance": ["Sri Lanka Insurance", "Co-operative Insurance", "Union Assurance"],
            "availableToday": False,
            "consultationFee": "LKR 3,200",
            "about": "Consultant Gynaecologist with strong focus on PCOS, hormonal disorders, and women's reproductive health management.",
            "credentials": [
                "MBBS - University of Peradeniya",
                "MD - Obstetrics & Gynaecology",
            ],
            "languages": ["Sinhala", "English"],
            "officeHours": "Mon-Fri: 8AM-4PM, Sat: 9AM-1PM",
            "nextAvailable": "Tomorrow, 2:00 PM",
            "categories": ["gynecology"],
            "telemedicine": True,
            "phone": "+94 81 234 5672",
        },
        {
            "id": 10,
            "name": "Prof. M Champika Gihan",
            "specialty": "Obstetrics & Gynaecology with Scanning",
            "rating": 4.8,
            "reviews": 312,
            "experience": "22 years",
            "location": "Kandy, Sri Lanka",
            "distance": "3.0 km",
            "image": "👩‍⚕️",
            "verified": True,
            "acceptsInsurance": ["SLIMHC", "Lanka IOC Health", "Ceylinco Healthcare"],
            "availableToday": True,
            "consultationFee": "LKR 4,500",
            "about": "Professor and Senior Consultant Obstetrician & Gynaecologist. Specialist in gynaecological ultrasound and PCOS diagnosis.",
            "credentials": [
                "MBBS - University of Peradeniya",
                "MD - Obstetrics & Gynaecology",
                "Diploma - Advanced Ultrasound",
                "Fellowship - Reproductive Medicine",
            ],
            "languages": ["Sinhala", "English"],
            "officeHours": "Mon-Fri: 8AM-5PM, Sat: 9AM-12PM",
            "nextAvailable": "Today, 3:30 PM",
            "categories": ["gynecology"],
            "telemedicine": True,
            "phone": "+94 81 234 5673",
        },
        {
            "id": 11,
            "name": "Dr. Sampath Gnanarathne",
            "specialty": "Obstetrics & Gynaecology",
            "rating": 4.7,
            "reviews": 201,
            "experience": "15 years",
            "location": "Kandy, Sri Lanka",
            "distance": "3.8 km",
            "image": "👨‍⚕️",
            "verified": True,
            "acceptsInsurance": ["Softlogic Insurance", "HNB Assurance", "Allianz Insurance"],
            "availableToday": False,
            "consultationFee": "LKR 3,300",
            "about": "Consultant Gynaecologist dedicated to PCOS management and women's reproductive health in the Kandy district.",
            "credentials": [
                "MBBS - University of Peradeniya",
                "MD - Obstetrics & Gynaecology",
            ],
            "languages": ["Sinhala", "English"],
            "officeHours": "Mon-Sat: 9AM-4PM",
            "nextAvailable": "Tomorrow, 9:30 AM",
            "categories": ["gynecology"],
            "telemedicine": True,
            "phone": "+94 81 234 5674",
        },
        {
            "id": 12,
            "name": "Prof. Asoka Karunananda",
            "specialty": "Obstetrics & Gynaecology with Scanning",
            "rating": 4.8,
            "reviews": 298,
            "experience": "23 years",
            "location": "Kandy, Sri Lanka",
            "distance": "2.9 km",
            "image": "👨‍⚕️",
            "verified": True,
            "acceptsInsurance": ["Ceylinco Life", "Sri Lanka Insurance", "MBSL Insurance"],
            "availableToday": True,
            "consultationFee": "LKR 4,800",
            "about": "Professor and Senior Consultant Obstetrician & Gynaecologist. Expert in PCOS diagnosis through ultrasound and reproductive health management.",
            "credentials": [
                "MBBS - University of Peradeniya",
                "MD - Obstetrics & Gynaecology",
                "Diploma - Ultrasound Imaging",
                "Fellowship - Reproductive Endocrinology",
            ],
            "languages": ["Sinhala", "Tamil", "English"],
            "officeHours": "Mon-Fri: 8AM-5PM, Sat: 9AM-1PM",
            "nextAvailable": "Today, 11:00 AM",
            "categories": ["gynecology"],
            "telemedicine": True,
            "phone": "+94 81 234 5675",
        },
        {
            "id": 13,
            "name": "Dr. Lasantha Rajapaksha",
            "specialty": "Obstetrics & Gynaecology with Scanning",
            "rating": 4.6,
            "reviews": 167,
            "experience": "13 years",
            "location": "Kandy, Sri Lanka",
            "distance": "3.6 km",
            "image": "👨‍⚕️",
            "verified": True,
            "acceptsInsurance": ["Janashakthi Insurance", "Ceylinco General", "AIA Insurance"],
            "availableToday": False,
            "consultationFee": "LKR 3,000",
            "about": "Consultant Gynaecologist with expertise in ultrasound imaging and PCOS detection and management.",
            "credentials": [
                "MBBS - University of Peradeniya",
                "MD - Obstetrics & Gynaecology",
                "Diploma - Ultrasound",
            ],
            "languages": ["Sinhala", "English"],
            "officeHours": "Tue-Sat: 8AM-4PM",
            "nextAvailable": "Tomorrow, 10:00 AM",
            "categories": ["gynecology"],
            "telemedicine": True,
            "phone": "+94 81 234 5676",
        },
        {
            "id": 14,
            "name": "Dr. P.G. Yohan Sachintha Silva",
            "specialty": "Consultant Obstetrics & Gynaecology with Scanning",
            "rating": 4.7,
            "reviews": 245,
            "experience": "17 years",
            "location": "Kandy, Sri Lanka",
            "distance": "3.1 km",
            "image": "👨‍⚕️",
            "verified": True,
            "acceptsInsurance": ["Sri Lanka Insurance", "Co-operative Insurance", "Union Assurance"],
            "availableToday": True,
            "consultationFee": "LKR 3,800",
            "about": "Senior Consultant Obstetrician & Gynaecologist specializing in PCOS diagnosis, ultrasound scanning, and reproductive health.",
            "credentials": [
                "MBBS - University of Peradeniya",
                "MD - Obstetrics & Gynaecology",
                "Diploma - Gynaecological Ultrasound",
            ],
            "languages": ["Sinhala", "English"],
            "officeHours": "Mon-Fri: 9AM-5PM, Sat: 10AM-2PM",
            "nextAvailable": "Today, 2:00 PM",
            "categories": ["gynecology"],
            "telemedicine": True,
            "phone": "+94 81 234 5677",
        },
        # Chilaw Doctors
        {
            "id": 15,
            "name": "Dr. Nayanan Ganesh",
            "specialty": "Obstetrics & Gynaecology (VOG)",
            "rating": 4.6,
            "reviews": 134,
            "experience": "12 years",
            "location": "Chilaw, Sri Lanka",
            "distance": "5.2 km",
            "image": "👨‍⚕️",
            "verified": True,
            "acceptsInsurance": ["SLIMHC", "Lanka IOC Health", "Ceylinco Healthcare"],
            "availableToday": True,
            "consultationFee": "LKR 2,500",
            "about": "Consultant Gynaecologist serving the western coastal region. Specialist in PCOS management and women's reproductive health.",
            "credentials": [
                "MBBS - University of Kelaniya",
                "MD - Obstetrics & Gynaecology",
            ],
            "languages": ["Sinhala", "Tamil", "English"],
            "officeHours": "Mon-Sat: 10AM-4PM",
            "nextAvailable": "Today, 11:00 AM",
            "categories": ["gynecology"],
            "telemedicine": True,
            "phone": "+94 32 234 5671",
        },
        {
            "id": 16,
            "name": "Dr. W.M.A.P.B. Walisundara",
            "specialty": "Obstetrics & Gynaecology (VOG)",
            "rating": 4.5,
            "reviews": 121,
            "experience": "11 years",
            "location": "Chilaw, Sri Lanka",
            "distance": "5.5 km",
            "image": "👩‍⚕️",
            "verified": True,
            "acceptsInsurance": ["Janashakthi Insurance", "Ceylinco General", "AIA Insurance"],
            "availableToday": False,
            "consultationFee": "LKR 2,300",
            "about": "Consultant Gynaecologist with focus on PCOS, hormonal disorders, and accessible women's health care in Chilaw region.",
            "credentials": [
                "MBBS - University of Kelaniya",
                "MD - Obstetrics & Gynaecology",
            ],
            "languages": ["Sinhala", "English"],
            "officeHours": "Mon-Fri: 9AM-3PM, Sat: 10AM-12PM",
            "nextAvailable": "Tomorrow, 1:00 PM",
            "categories": ["gynecology"],
            "telemedicine": True,
            "phone": "+94 32 234 5672",
        },
    ]

    for doctor in doctors:
        doctor.setdefault("email", _derive_doctor_email(doctor["name"]))

    return doctors


def find_doctor_by_id(doctor_id: int) -> Optional[Dict[str, Any]]:
    for doctor in get_doctors_catalog():
        if int(doctor.get("id")) == int(doctor_id):
            return doctor
    return None
